#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED

#define IDS_SUSPEND 101
#define IDS_NEXT_LAYOUT 102
#define IDS_PREV_LAYOUT 103
#define IDS_EXIT 104

#define IDI_ICON_ON 151
#define IDI_ICON_OFF 152

#endif // RESOURCE_H_INCLUDED
